//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int codigo { get; set; }
        public Nullable<int> venta { get; set; }
        public string raz_soc { get; set; }
        public string ruc { get; set; }
        public Nullable<double> pretotal { get; set; }
        public Nullable<double> igv { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual Venta Venta1 { get; set; }
    }
}
