//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.Boleta = new HashSet<Boleta>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int codigo { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> producto { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> contribuyente { get; set; }
        public Nullable<int> cliente { get; set; }
        public string sede { get; set; }
        public string placa { get; set; }
        public string observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleta> Boleta { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Contribuyente Contribuyente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Producto Producto1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
